Backport a50725db2ab621e1a17cb5505f78e4bc73972a27
openjdk/jdk11u-dev pull request #1020
Opened 2022-04-07 15:34 UTC by andrewazores

Backport commit [a50725db2ab621e1a17cb5505f78e4bc73972a27](https://github.com/openjdk/jdk/commit/a50725db) for [JDK-8254001](https://bugs.openjdk.java.net/browse/JDK-8254001), enhancement to cgroups interface parsing and version detection.

The patch applied mostly cleanly with only two minor conflicts in `CgroupV1Subsystem.java`. These conflicts were simply hunks that failed to apply because the surrounding context did not match due to later changes in the internal implementation that are not present in JDK11. Since the patch being backported wholly replaces or removes these implementations anyway, my resolution was to simply remove the old implementation and accept the new implementation from the backport patch.

2022-04-07 15:43 UTC, andrewazores commented
/covered

2022-04-12 13:09 UTC, jerboaa requested changes
Once change required due to an out-of-order backport to 11u.

2022-04-13 15:13 UTC, andrewazores commented on src/java.base/linux/classes/jdk/internal/platform/CgroupSubsystemFactory.java
> +            selfCgroupLines.map(line -> line.split(":"))
Okay, so rather than backporting the whole 8272124 I should just cherry-pick out that single fix to this file for inclusion in this PR?

2022-04-15 08:56 UTC, jerboaa approved these changes
LGTM. Hopefully we'll get the OCA verification resolved soon.

2022-04-22 09:51 UTC, jerboaa commented
@robilad Gentle ping?

2022-04-28 08:35 UTC, jerboaa commented
@andrewazores OCA is now approved. Please request for approval in the bug. See step 6 in: https://wiki.openjdk.java.net/display/JDKUpdates/How+to+contribute+a+fix

2022-04-29 06:45 UTC, GoeLin commented
Hi, can you please enable the GHA actions and Pre-submit tests for this repo so they run next time? Thanks

2022-04-29 14:47 UTC, andrewazores commented
Hi @GoeLin , I have enabled Actions on my fork. Is there a way to trigger the tests to run now?

2022-04-29 15:31 UTC, andrewazores commented
/integrate

2022-04-29 15:41 UTC, jerboaa commented
/sponsor

2022-04-29 15:43 UTC, closed without merging