8247907: XMLDsig logging does not work
openjdk/jdk11u-dev pull request #1129
Opened 2022-06-08 04:28 UTC by caojoshua

Not a clean backport, due to the following:
* [these lines](https://github.com/openjdk/jdk11u-dev/blob/f700d37d2b3d8c23d50defc19853c68bb60027ab/src/java.xml.crypto/share/classes/com/sun/org/slf4j/internal/Logger.java#L80-L83) are not included in the original patch
* Use HexDumpEncoder instead of HexPrinter, because HexPrinter does not exist in JDK11
* Different copyright years

Changes pass the new jtreg test.

2022-06-10 17:56 UTC, phohensee requested changes
The copyright date maintainer policy as I understand it is to update the year to what is in the original commit if that's later than what's in the target file, not to the current year. So in this case, use 2020 rather than 2022.

Please document in this PR the use of "warn(String s, Object... o)" in 11 that doesn't exist in 16.

Otherwise lgtm.

2022-06-10 22:47 UTC, caojoshua commented
> The copyright date maintainer policy as I understand it is to update the year to what is in the original commit if that's later than what's in the target file, not to the current year. So in this case, use 2020 rather than 2022.
> 
> Please document in this PR the use of "warn(String s, Object... o)" in 11 that doesn't exist in 16.
> 
> Otherwise lgtm.

Thanks for the review. I changed the years to 2020 and updated the original PR description

2022-06-16 17:36 UTC, phohensee approved these changes
Lgtm. Please tag the issue with jdk11u-fix-request and a Fix Request (11u) comment.

2022-07-05 16:55 UTC, phohensee commented
/sponsor

Failing pre-submit test appears unrelated.

2022-07-05 16:56 UTC, closed without merging