Backport d3e781de086d557a88105da965ff8a7f9126019c
openjdk/jdk11u-dev pull request #1191
Opened 2022-06-30 15:50 UTC by GoeLin

I backport this for parity with 11.0.17-oracle.

I had to resolve because bool allow_inline is not 
defined in 11. That was introcuded for a debugging
feature, we don't need it here.

2022-07-04 10:43 UTC, TheRealMDoerr approved these changes
Good. Feel free to fix indentation before integrating.

2022-07-04 10:43 UTC, TheRealMDoerr commented on src/hotspot/share/opto/callGenerator.cpp
> +         print_inlining_failure(C, callee, jvms->depth() - 1, jvms->bci(),
Indentation looks odd.

2022-07-05 09:15 UTC, GoeLin commented on src/hotspot/share/opto/callGenerator.cpp
> +         print_inlining_failure(C, callee, jvms->depth() - 1, jvms->bci(),
Fixed, thanks.

2022-07-07 11:50 UTC, RealCLanger requested changes

2022-07-13 10:26 UTC, GoeLin commented on src/hotspot/share/opto/callGenerator.cpp
> +         print_inlining_failure(C, callee, jvms->depth() - 1, jvms->bci(),
Fixed.

2022-07-15 10:45 UTC, GoeLin commented
/integrate

2022-07-15 10:46 UTC, closed without merging