8281181: Do not use CPU Shares to compute active processor count
openjdk/jdk11u-dev pull request #1196
Opened 2022-07-01 13:25 UTC by MBaesken

jdk11u-dev backport of 8281181,  copyright headers needed adjustment and minor diffs in strides

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires a CSR request to be approved

### Issues
 * [JDK-8281181](https://bugs.openjdk.org/browse/JDK-8281181): Do not use CPU Shares to compute active processor count
 * [JDK-8286220](https://bugs.openjdk.org/browse/JDK-8286220): Do not use CPU Shares to compute active processor count (**CSR**)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u-dev pull/1196/head:pull/1196` \
`$ git checkout pull/1196`

Update a local copy of the PR: \
`$ git checkout pull/1196` \
`$ git pull https://git.openjdk.org/jdk11u-dev pull/1196/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1196`

View PR using the GUI difftool: \
`$ git pr show -t 1196`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u-dev/pull/1196.diff">https://git.openjdk.org/jdk11u-dev/pull/1196.diff</a>

</details>

2022-07-04 09:46 UTC, jerboaa requested changes
Almost good to go. File `src/hotspot/os/linux/cgroupSubsystem_linux.cpp` is missing the copyright year update from the original patch and a tiny nit below.

2022-07-04 09:46 UTC, jerboaa commented on test/hotspot/jtreg/containers/docker/TestCPUAwareness.java
> +        if (useContainerCpuShares) opts.addJavaOpts("-XX:+UseContainerCpuShares");
The JDK 18u patch has an additional `System.out.println("useContainerCpuShares = " + useContainerCpuShares);` on line 210 of this file which is missing in this backport.

2022-07-04 10:56 UTC, MBaesken commented
Thanks Severin for the remarks. I added the copyright year and the test output line,

2022-07-04 12:06 UTC, jerboaa approved these changes
LGTM.

2022-07-04 12:13 UTC, jerboaa commented
@MBaesken FYI: I've created https://github.com/openjdk/jdk11u-dev/pull/1197 for the `shares/periods` typo in one of the tests.

2022-07-05 08:16 UTC, MBaesken commented
/integrate

2022-07-05 08:17 UTC, closed without merging