8290813 jdk/nashorn/api/scripting/test/ScriptObjectMirrorTest.java fa…
openjdk/jdk11u-dev pull request #1255
Opened 2022-07-21 14:17 UTC by gdams

Tested locally and passes on my machine

2022-07-21 14:54 UTC, szegedi requested changes

2022-07-21 14:54 UTC, szegedi commented on test/nashorn/src/jdk/nashorn/api/scripting/test/ScriptObjectMirrorTest.java
> +        assertEquals(new Double(42.0), obj.to(Double.class));
```suggestion
        assertEquals(Double.valueOf(42.0), obj.to(Double.class));
```
`Double` constructor is deprecated since Java 9.

2022-07-21 15:00 UTC, RealCLanger approved these changes
LGTM. Double.valueOf seems the right thing.

2022-07-21 15:06 UTC, szegedi approved these changes

2022-07-22 09:39 UTC, gdams commented
/integrate

2022-07-22 09:46 UTC, RealCLanger commented
/sponsor

2022-07-22 09:47 UTC, closed without merging