Backport d577d9c678b9b14227731d9cf7b2328100d66428
openjdk/jdk11u-dev pull request #175
Opened 2021-07-29 17:30 UTC by zhengyu123

I would like to backport this patch to 11u. This patch contains missing test from JDK-8225583, which is a Oracle parity backport.

The backport is clean. And the test passes with  JDK-8225583.

2021-07-30 04:43 UTC, RealCLanger commented
This PR also contains the commit for JDK-8225583, so it's not correct. Once #174 is merged you should probably repair this PR...

2021-08-03 21:43 UTC, RealCLanger commented
@zhengyu123 Can you update the PR to only contain the commit of JDK-8226319? Force push should be ok in this case. Then the PR should probably get marked as clean...

2021-08-09 06:30 UTC, shipilev requested changes
Wait, there are other changes in this PR, not only the test. Please see what is up here.

2021-08-09 13:02 UTC, zhengyu123 commented
Oops, the patch contains dependency. After rebase, the branch now has conflicts. Close this PR and redo.

2021-08-09 13:02 UTC, closed without merging