Backport 409382ba4b43bf48ed0086020dd20641effd35b6
openjdk/jdk11u-dev pull request #1780
Opened 2023-02-27 17:58 UTC by asgibbons

Backporting because this change results in ~3x performance improvement in AES-CTR.

Risk is low.  Tested with tier1 and benchmark.

The PR does not backport cleanly.  The buffer name was changed, but functionally remains the same.

2023-02-27 21:41 UTC, RealCLanger approved these changes
LGTM

2023-02-27 21:41 UTC, RealCLanger commented
can you please run GHA

2023-02-27 21:46 UTC, asgibbons commented
Noob here - what is GHA?

2023-02-28 15:22 UTC, RealCLanger commented
> Noob here - what is GHA?

GHA= GitHub Actions. You have to enable it in your [repository fork](https://github.com/asgibbons/jdk11u-dev/actions). Then you will also be able to trigger the run for your PR branch.

2023-03-01 08:15 UTC, RealCLanger requested changes
Hm after your merges the resulting change looks incorrect.

2023-03-01 22:17 UTC, asgibbons commented
@RealCLanger - Sorry for the churn.  I had a slight mixup in the myriad of JDK trees I'm concurrently maintaining.  I fixed the issue and manual testing along with tier1 testing have successfully completed.

Please review and approve if this is acceptable.

2023-03-02 22:08 UTC, sviswa7 commented
@ascarpino Could you please help review this backport CR?

2023-03-05 21:18 UTC, RealCLanger requested changes
I had a closer look now. Overall it seems ok. Could you maybe rename outWithPadding to internalOutput? That would bring the code closer to head and seems the more logical name for the buffer. Thanks.

2023-03-05 21:18 UTC, RealCLanger commented on src/java.base/share/classes/com/sun/crypto/provider/CipherCore.java
> +            if(outWithPadding != null) {
Please add a space after `if`

2023-03-06 15:51 UTC, RealCLanger requested changes

2023-03-06 15:51 UTC, RealCLanger commented on src/java.base/share/classes/com/sun/crypto/provider/CipherCore.java
> -    private int unpad(int outLen, byte[] outWithPadding)
Here the variable should remain outWithPadding.

2023-03-06 15:51 UTC, RealCLanger commented on src/java.base/share/classes/com/sun/crypto/provider/CipherCore.java
> -        int padStart = padding.unpad(outWithPadding, 0, outLen);
Same here.

2023-03-06 17:04 UTC, RealCLanger commented
Thanks. This looks good. I'll run it through SAP'S nightlies and will hopefully approve tomorrow when no regressions spotted.

2023-03-06 17:30 UTC, asgibbons commented
Thank you very much @RealCLanger !

2023-03-06 19:05 UTC, ascarpino commented
The backport looks consistent with what was put in recent releases.

2023-03-06 19:33 UTC, ascarpino commented
Something that should be verified is that this doesn't expose failed auth tag decrypted GCM data or other GCM decryption.  There maybe some unexpected differences as this change was after GCM separated from CipherCore in 17.  I believe GCM still uses CipherCore in 11.

2023-03-06 21:27 UTC, asgibbons commented
Thanks, @ascarpino.  Are there any tests I can run to verify that no GCM data have been exposed?  It appears to me that there's one place where decrypted data could be leaked (ShortBufferException), but this is the same in newer versions.

2023-03-07 07:59 UTC, RealCLanger approved these changes
Looks good from my perspective now. SAP tests passed. Can't say anything to the GCM topic brought up by @ascarpino, though.

2023-03-07 19:20 UTC, asgibbons commented
@ascarpino I have been looking to see whether any data could be potentially leaked as a result of my change and cannot envision such a scenario.  It appears to me that my change is functionally identical to what it would be without the change.  Can you please provide more details?  Thanks.

2023-03-09 15:46 UTC, asgibbons commented
I believe there is no additional risk to data leakage as the result of this change, so I'm proposing integration.  Thanks.

/integrate

2023-03-10 09:17 UTC, RealCLanger commented
> I believe there is no additional risk to data leakage as the result of this change, so I'm proposing integration. Thanks.
> 
> /integrate

ok

/sponsor

2023-03-10 09:20 UTC, closed without merging