Backport 03f25a9c6924430ec4063b801b2b6ca55b9067c9
openjdk/jdk11u-dev pull request #1825
Opened 2023-04-07 13:00 UTC by alograg

8299602: blocked threads with KeepAliveCache.

I followed the steps that helped me carry out this pull-request.

REF/: https://mail.openjdk.org/pipermail/jdk-updates-dev/2023-February/020439.html

Thanks to @GoeLin and @jerboaa

2023-04-07 13:06 UTC, alograg commented
/covered

2023-04-08 15:26 UTC, theRealAph commented on src/java.base/share/classes/sun/net/www/http/KeepAliveCache.java
> +                new GetIntegerAction(keepAliveProp + type, -1)).intValue();
```suggestion
            new GetIntegerAction(keepAliveProp + type, -1)).intValue();
```

2023-04-08 15:28 UTC, theRealAph commented on src/java.base/share/classes/sun/net/www/http/KeepAliveCache.java
> +        implements Runnable {
```suggestion
    extends HashMap<KeepAliveKey, ClientVector>
    implements Runnable {
```

2023-04-08 15:29 UTC, theRealAph commented on src/java.base/share/classes/sun/net/www/http/KeepAliveCache.java
> +                    .intValue();
```suggestion
                new GetIntegerAction("http.maxConnections", MAX_CONNECTIONS))
                .intValue();
```

2023-04-08 15:42 UTC, theRealAph commented
I just looked at https://github.com/openjdk/jdk/pull/10401/files , and I see that it does not change white space in otherwise unchanged files. Please remove all white space-only changes from this patch. It'll make this patch easier to review.

2023-04-11 08:03 UTC, alograg commented
> I just looked at https://github.com/openjdk/jdk/pull/10401/files , and I see that it does not change white space in otherwise unchanged files. Please remove all white space-only changes from this patch. It'll make this patch easier to review.

Thanks, this was done automatically by my IDE, sorry.

2023-04-14 16:11 UTC, robilad commented
Hi, please send an e-mail to Dalibor.Topic@oracle.com so that I can mark your account as verified.

2023-04-25 13:53 UTC, jerboaa requested changes
This patch is pretty hard to review since it includes many unrelated changes. Please try to only make *necessary* adaptations and explain why those changes needed to be made.

Perhaps it makes more sense to start over by applying the JDK 17u patch and adjusting it until it works and you're confident the patch does what it's supposed to do. It's important to configure your editor in a way to not modify code that isn't being touched by the patch. Unrelated formatting changes are not OK in a backport.

While the JDK 17u patch builds on https://bugs.openjdk.org/browse/JDK-8229867, this backport should not include those changes. It should use the old synchronization scheme instead.

2023-04-25 13:53 UTC, jerboaa commented on src/java.base/share/classes/sun/net/www/http/KeepAliveCache.java
> +    private final ReentrantLock cacheLock = new ReentrantLock();
This got introduced in JDK 16 with https://bugs.openjdk.org/browse/JDK-8229867, please don't introduce such changes in a backport. The patch needs to be done without JDK-8229867 being present in JDK 11u

2023-04-25 13:53 UTC, jerboaa commented on src/java.base/share/classes/sun/net/www/http/KeepAliveCache.java
> +    }
Unrelated style change.

2023-04-25 13:53 UTC, jerboaa commented on src/java.base/share/classes/sun/net/www/http/KeepAliveCache.java
> +    @SuppressWarnings("removal")
Those annotations aren't part of the original change.

2023-04-25 13:53 UTC, jerboaa commented on src/java.base/share/classes/sun/net/www/http/KeepAliveCache.java
> +     * called by a clientVector thread when all its connections have timed out
Unrelated style change

2023-04-25 13:53 UTC, jerboaa commented on src/java.base/share/classes/sun/net/www/http/KeepAliveCache.java
> +        assert cacheLock.isHeldByCurrentThread();
Not part of the original changeset. Please keep the port as close as possible to the JDK 17 version. Caveats such as JDK-8229867 apply.

2023-05-24 09:40 UTC, alograg commented
> This patch is pretty hard to review since it includes many unrelated changes. Please try to only make _necessary_ adaptations and explain why those changes needed to be made.
> 
> Perhaps it makes more sense to start over by applying the JDK 17u patch and adjusting it until it works and you're confident the patch does what it's supposed to do. It's important to configure your editor in a way to not modify code that isn't being touched by the patch. Unrelated formatting changes are not OK in a backport.
> 
> While the JDK 17u patch builds on https://bugs.openjdk.org/browse/JDK-8229867, this backport should not include those changes. It should use the old synchronization scheme instead.

Hi @jerboaa 

Where do I find the documentation for "the old synchronization scheme" ?

I am trying to make the requested changes but I would like to see how it is done to see if it is better than the manual change.

Thanks

2023-05-24 11:39 UTC, jerboaa commented
> > This patch is pretty hard to review since it includes many unrelated changes. Please try to only make _necessary_ adaptations and explain why those changes needed to be made.
> > Perhaps it makes more sense to start over by applying the JDK 17u patch and adjusting it until it works and you're confident the patch does what it's supposed to do. It's important to configure your editor in a way to not modify code that isn't being touched by the patch. Unrelated formatting changes are not OK in a backport.
> > While the JDK 17u patch builds on https://bugs.openjdk.org/browse/JDK-8229867, this backport should not include those changes. It should use the old synchronization scheme instead.
> 
> Hi @jerboaa
> 
> Where do I find the documentation for "the old synchronization scheme" ?

Look at https://github.com/openjdk/jdk/commit/65393a09 the change done as part of https://bugs.openjdk.org/browse/JDK-8229867. In essence it's changing `synchronized` methods to use `java.util.concurrent.locks` API instead.

> I am trying to make the requested changes but I would like to see how it is done to see if it is better than the manual change.

Someone else has done another backport of this change. See https://github.com/openjdk/jdk11u-dev/pull/1890 perhaps coordinate with that contributor?

2023-05-24 13:24 UTC, alograg commented
I think the #1890 code of  @PoojaDP-23 is more faithful to the original correction code.
Thank very much for ton review @jerboaa

2023-05-24 13:24 UTC, closed without merging