Backport e71557a2d9e3a3d84fb2d4cea02c4364258f0249
openjdk/jdk11u-dev pull request #1861
Opened 2023-05-05 15:18 UTC by RealLucy

I back port this for parity with Oracle JDK 11.0.20.

Backport didn't integrate cleanly. There were copyright statement issues as well as incompatible import statement sequences.

Reviews are very welcome.

SAP-internal tests don't show any issues.

2023-05-10 08:46 UTC, RealCLanger requested changes
Looks good overall but when resolving the copyrights, don't date back the year, rather keep the more current years 😄

2023-05-10 10:41 UTC, RealLucy commented
@RealCLanger Thank you for the review. 
Will integrate once the tests have completed successfully.

2023-05-10 13:59 UTC, RealLucy commented
/integrate

2023-05-10 14:00 UTC, closed without merging

2023-05-11 10:36 UTC, GoeLin commented
Hi Lutz, please do not push without jdk11u-fix-request!
You can easily monitor approved changes by using this filter: https://bugs.openjdk.org/browse/JDK-8305400?filter=36412