Backport e81ee784d37b89605b8fb8c5107dec6fcb1ed022
openjdk/jdk11u-dev pull request #2037
Opened 2023-07-12 07:15 UTC by luchenlin

I backport this for parity with 11.0.21-oracle.
test/jdk/sun/net/www/protocol/https/ChunkedOutputStream.java
Resolved due to context
test/jdk/sun/net/www/protocol/https/HttpCallback.java
Copyright

2023-07-17 22:10 UTC, phohensee requested changes
There's no reason to backport testPlainText if it's not invoked. getAuthority went in as part of [JDK-8268464](https://bugs.openjdk.org/browse/JDK-8268464), for which the patch is fairly large but worth consideration. If you don't want to do that backport first, please include getAuthority from it and use it for this backport.

2023-07-19 05:26 UTC, luchenlin commented
> There's no reason to backport testPlainText if it's not invoked. getAuthority went in as part of [JDK-8268464](https://bugs.openjdk.org/browse/JDK-8268464), for which the patch is fairly large but worth consideration. If you don't want to do that backport first, please include getAuthority from it and use it for this backport.

Since [JDK-8268464](https://bugs.openjdk.org/browse/JDK-8268464) will remove TestHttpsServer.java, i have updated and add the getAuthority() method for TestHttpsServer, which seems more reasonable。

2023-07-19 14:45 UTC, phohensee approved these changes
Makes sense.

2023-07-26 02:40 UTC, luchenlin commented
/integrate

2023-07-26 06:21 UTC, GoeLin commented
/sponsor

2023-07-26 06:23 UTC, closed without merging