Backport 837928ba7955dbfd4a9c966209c3469c0fb5e195
openjdk/jdk11u-dev pull request #2040
Opened 2023-07-13 08:30 UTC by kurashige23

Hi,

This is a backport of JDK-8222323: ChildAlwaysOnTopTest.java fails with "RuntimeException: Failed to unset alwaysOnTop"

ChildAlwaysOnTopTest.java is not excluded by ProblemList in 11u. But I detected the test failed on Windows Server 2016.

Also original patch does not apply cleanly to 11u, because the fix uses "StringBuffer.isEmpty()" published in JDK15. I fixed the test so as not to use "StringBuffer.isEmpty()".

Thanks.

2023-07-13 15:16 UTC, phohensee requested changes
Copyright date s/b 2022, not 2023. Otherwise good.

2023-07-14 01:46 UTC, kurashige23 commented
@phohensee Thanks. I fixed it.

2023-07-14 11:50 UTC, phohensee approved these changes
Looks good now. Thanks for doing the backport.

2023-07-19 03:11 UTC, kurashige23 commented
@phohensee Thanks for the tagging.

2023-07-20 00:58 UTC, kurashige23 commented
/integrate

2023-07-20 13:31 UTC, phohensee commented
/sponsor

2023-07-20 13:33 UTC, closed without merging