Backport 62defc3dfc4b9ba5adfe3189f34fe8b3f59b94a0
openjdk/jdk11u-dev pull request #2087
Opened 2023-08-17 19:39 UTC by gnu-andrew

GHA is currently broken in 11u-dev as the referenced Ubuntu gcc package, `10.3.0-1ubuntu1~20.04`, is no longer available.

Rather than bumping this yet again, this PR suggests dropping the specific version as we did some time ago in 8u. The requirement still specifies a specific major version of GCC. It just means the dependency isn't broken every time Ubuntu bumps to a new minor release or even just makes a minor change to the package alone.

Note that the current setup does not guarantee sticking with an exact version of GCC anyway, because - as seen by the current GHA breakage - older versions get removed from the package repository. All we get from this exact version requirement is sporadic breakage. If we truly want a static version of GCC, we need to provide our own as we do with the JDK.

2023-08-17 19:58 UTC, mrserb commented
maybe we can do the same for 17?

2023-08-17 19:59 UTC, mrserb approved these changes

2023-08-17 20:31 UTC, mrserb commented
[build-cross-compile.yml](https://github.com/openjdk/jdk11u-dev/blob/master/.github/workflows/build-cross-compile.yml#L38) should be updated as well?

2023-08-17 21:29 UTC, simonis approved these changes
Thanks for the quick fix.

Looks good to me.

2023-08-17 21:37 UTC, mrserb requested changes
Yeah cross compilation should be updated.

2023-08-18 00:26 UTC, gnu-andrew commented
> Yeah cross compilation should be updated.

Good catch. My `grep` didn't catch that as the version is set indirectly as a default value.

For the current 11u version of `build-cross-compile.yml`, we just drop `apt-gcc-version` and `apt-gcc-cross-suffix` altogether as they only relate to the specific version e.g. we now ask for `gcc-10-s390x-linux-gnu` not `gcc-10-s390x-linux-gnu=10.3.0-1ubuntu1~20.04cross1` (https://packages.ubuntu.com/jammy/gcc-10-s390x-linux-gnu)

2023-08-18 00:28 UTC, gnu-andrew commented
> maybe we can do the same for 17?

I'm happy to propose it if this goes through. It's not as critical as https://github.com/openjdk/jdk17u/commit/260f28761a87553fd634615df5ba3db5b76ae692 was already added there. The need for things like [JDK-8313428](https://bugs.openjdk.org/browse/JDK-8313428) included in that change is exactly why I think this is the better long-term option.

2023-08-18 01:00 UTC, mrserb approved these changes

2023-08-18 02:40 UTC, gnu-andrew commented
Thanks for the reviews. I've flagged the bug for 11u approval.

2023-08-18 17:31 UTC, gnu-andrew commented
I see `jdk11u-fix-yes`.
/integrate

2023-08-18 17:32 UTC, closed without merging

2023-08-21 11:11 UTC, shipilev commented
I don't think we should be doing these point fixes that diverge 11u GHA, and effectively do forward-ports from 8u. If we want to change how minor GCC versions are handled, we need to do this in mainline, and then back-port that change properly to 21u, 17u, 11u. 8u is harder, because GHA is way backwards here, missing major GHA rewrites.

But for 11u we should just keep maintaining the parity with mainline. In other words, do 11u GHA updates like we did for 17u: https://github.com/openjdk/jdk11u-dev/pull/2090. That PR effectively reverts this one.