Backport 59d9d9fcb93c26dd8931d70934b889245b050acc
openjdk/jdk11u-dev pull request #2208
Opened 2023-10-24 06:22 UTC by tstuefe

Backported for parity with Oracle and as preparation to fix https://bugs.openjdk.org/browse/JDK-8312182.

Backport is unclean, but the difference is minor. I had to adjust hunks in `os::large_page_init()` since the surrounding coding changed a lot since JDK 11.

2023-10-24 12:29 UTC, tstuefe commented
@gnu-andrew maybe ?

2023-10-25 23:09 UTC, phohensee requested changes
At the start of os::large_page_init(), there's an extra blank line after the method signature. Otherwise fine.

2023-11-14 08:31 UTC, tstuefe commented
> At the start of os::large_page_init(), there's an extra blank line after the method signature. Otherwise fine.

Thank you, Paul!

2023-11-14 18:15 UTC, phohensee approved these changes

2024-01-10 11:48 UTC, closed without merging

2025-06-25 13:21 UTC, kurashige23 commented
@tstuefe 

HI, 

I am facing a bug described in [JDK-8312182](https://bugs.openjdk.org/browse/JDK-8312182) and would like to apply the JDK-8312182's fix to jdk11 and jdk8.

Could you reopen this PR and issue a Fix Request?

Thanks.

2025-09-04 05:04 UTC, kurashige23 commented
@tstuefe 

Sorry to bother you, but I'd appreciate it if you could check https://github.com/openjdk/jdk11u-dev/pull/2208#issuecomment-3004754545.
If you don't have time to reopen and work on this, I will consider creating a new pull request myself.

Thanks.

2025-09-04 16:14 UTC, phohensee commented
@kurashige23, you could also just file new PRs.

2025-10-21 11:15 UTC, tkiriyama commented
@kurashige23 , @phohensee 
I've created a new pull request. I would appreciate it if you could take a look.
https://github.com/openjdk/jdk11u-dev/pull/3106