backport of c0dce25756911ce49e7d8b034d5f12a25fc3c81d
openjdk/jdk11u-dev pull request #2712
Opened 2024-05-16 19:43 UTC by dhanalla

backport of c0dce25756911ce49e7d8b034d5f12a25fc3c81d

2024-06-13 15:52 UTC, dhanalla commented
Adding a comment to keep this PR active.

2024-06-20 14:21 UTC, TheRealMDoerr requested changes
Sorry for the delay. I had started a review and forgot to finish it.

2024-06-25 23:09 UTC, dhanalla commented on test/hotspot/jtreg/serviceability/sa/TestInstanceKlassSizeForInterface.java
> +import java.util.Arrays;
@TheRealMDoerr, Thanks for reviewing the PR.

2024-06-27 07:58 UTC, TheRealMDoerr approved these changes
Thanks!

2024-06-27 16:20 UTC, dhanalla commented
/integrate

2024-06-27 16:29 UTC, TheRealMDoerr commented
/sponsor

2024-06-27 16:30 UTC, closed without merging