Backport 7144027dff495b623428bd9cd891c0ed912035a4
openjdk/jdk11u-dev pull request #2936
Opened 2024-09-19 08:59 UTC by vieiro

The `macos-11`  github runners [were deprecated and removed in June 2024](https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/) , making the `macos` tests to hang in `openjdk11u-dev` (and other OpenJDK repositories).

[JDK-8335793 GHA: Bump macOS and Xcode versions](https://bugs.openjdk.org/browse/JDK-8335793) upgraded the version [from `macos-11` to `macos-13`](https://github.com/openjdk/jdk11u-dev/pull/2835).  This upgrade in github runners required a long list of changes in `openjdk11u-dev` that proved difficult to review.

In order to ease the review process this PR downgrades the version of github runners in `jdk11u-dev` from the current `macos-13` to `macos-12` and `xcode-13.4.1`. This will require a single backport of [JDK-8299254 Support dealing with standard assert macro](https://bugs.openjdk.org/browse/JDK-8299254) (a follow-up to this PR), making the review process easier.

Once the github actions are running again in `macos-12` an upgrade to `macos-13` could be performed, if required, with some more additional PRs.

2024-09-23 16:41 UTC, vieiro commented
Filed as https://bugs.openjdk.org/browse/JDK-8318039

2024-09-23 17:02 UTC, jerboaa commented
> Filed as https://bugs.openjdk.org/browse/JDK-8318039

Still `8318039`?

2024-09-24 06:55 UTC, vieiro commented
https://bugs.openjdk.org/browse/JDK-8340671

2024-09-24 11:06 UTC, jerboaa approved these changes
Thanks.

2024-09-24 11:08 UTC, jerboaa commented
On second thought, this PR is labelled backport. It's an 11u specific bug. Please close this PR and open a new - non-backport pr.

2024-09-24 11:09 UTC, jerboaa requested changes
We need a 11u non-backport PR for this.

2024-09-24 19:56 UTC, closed without merging

2024-09-24 20:11 UTC, vieiro commented
Reopened as https://github.com/openjdk/jdk11u-dev/pull/2940