Backport 04b98fd1df8438f892e48c2425a8d75dfbd1ccc2
openjdk/jdk11u-dev pull request #373
Opened 2021-09-17 14:47 UTC by TheRealMDoerr

Backport of JDK-8222446. Doesn't apply cleanly. Mainly because JVMCI is different, but also other context changes.

2021-09-17 21:50 UTC, phohensee requested changes
Missing copyright date updates in ciEnv.hpp, systemDictionary.*, dependencies.hpp,  jvmciEnv.*, method.cpp, callGenerator.cpp, parse1.cpp, jvmtiRedefineClasses.cpp, and vmStructs.cpp. Otherwise lgtm.

2021-09-20 08:56 UTC, TheRealMDoerr commented
@phohensee Thank you for reviewing my backport! The original change doesn't modify the Copyright headers in these files. So, I don't think my backport shouldn't do that. That would create further conflicts for future backports. We usually only change Copyright headers in backport PRs when the original change does so.

2021-09-20 14:00 UTC, phohensee commented
My understanding is that it's a legal requirement (but, ianal), to update a file's copyright date to that of the latest patch that affected it, regardless of the effect on future backports. In this case, the reason the original patch didn't update the copyright is because the not-affected files were already at 2019 when the original patch was applied. But, best to ask on the list, I suppose.

2021-09-21 06:18 UTC, GoeLin commented
Hi Paul, 
so far we never updated the Copyrights. If there are conflicts, we resolve to the latest date.
But if there are no conflicts, or if we have to resolve the file and the file has no Copyright change
in the original, or if the copyright is changed but the new year is in the past, we do not adapt it. 
Oracle handles this similarly.
Best regards,
  Goetz

2021-09-22 16:31 UTC, phohensee approved these changes
If that's the case (and in any case!) a note should be added to the updates wiki.

2021-09-22 16:56 UTC, TheRealMDoerr commented
Thanks again for the review! Right, would be good to have that documented. I couldn't even find official Copyright year update rules for the jdk project.
/integrate

2021-09-22 16:58 UTC, closed without merging