8274860: gcc 10.2.1 produces an uninitialized warning in sharedRuntimeTrig.cpp
openjdk/jdk11u-dev pull request #489
Opened 2021-10-06 21:32 UTC by caojoshua

Fix the warning by initializing `fq` to an array of zeroes.

2021-11-08 00:35 UTC, caojoshua commented
As suggested in https://github.com/openjdk/jdk/pull/6220, pushed changes to ignore warning.

I think we should make changes directly to JDK11, instead of JDK18. The warning is disabled in JDK18 and JDK15.

2021-11-15 23:09 UTC, phohensee approved these changes
Lgtm. Thanks for investigating 18.

2021-11-16 19:27 UTC, phohensee requested changes
compilerWarnings.cpp needs to set  PRAGMA_MAYBE_UNINITIALIZED_IGNORED to null if it's undefined, the same way as is PRAGMA_STRINGOP_TRUNCATION_IGNORED.

2021-11-17 20:18 UTC, phohensee approved these changes
Lgtm.

2021-11-19 17:20 UTC, caojoshua commented
/integrate

2021-11-19 18:04 UTC, phohensee commented
/sponsor

2021-11-19 18:13 UTC, closed without merging