Backport c0cda1db4fe74b86faa12136336bdf98c96758d2
openjdk/jdk11u-dev pull request #572
Opened 2021-11-01 15:53 UTC by Larry-N

Performance enhancement. Tested with tier-2.

2021-11-09 17:03 UTC, RealCLanger requested changes
The .gitignore file should not be deleted...

2021-11-10 13:18 UTC, Larry-N commented
Sorry, thanks.

2021-11-17 13:29 UTC, RealCLanger commented on src/java.base/share/classes/javax/security/auth/login/LoginContext.java
> +                            @SuppressWarnings("removal")
I guess in 11 you don't need this @SuppressWarnings("removal") directive since the deprecation for Security Manager was done later.

2021-11-17 13:30 UTC, RealCLanger commented
I looked at this now. Except from the minor comment regarding the SuppressWarnings, it looks good to me. I'll run it through our nightlies once more.

2021-11-17 14:49 UTC, Larry-N commented
Thanks, Christoph. I've removed redundant SupressWarning

2021-11-18 12:26 UTC, RealCLanger approved these changes
LGTM

2021-11-22 13:23 UTC, Larry-N commented
/integrate

2021-11-22 16:06 UTC, RealCLanger commented
/sponsor

2021-11-22 16:08 UTC, closed without merging