Backport cddc6ce44695cba4614c3405eb2b194d7c76489b
openjdk/jdk11u-dev pull request #709
Opened 2021-12-08 16:32 UTC by zhengyu123

A clean backport for parity with Oracle 11.0.15. 

Low risk bug fix in TLS code which can improve JDK performance in this area.

2021-12-09 10:35 UTC, TheRealMDoerr requested changes
Please explain your ProblemList change or remove it if it was done by mistake.

2021-12-09 20:29 UTC, zhengyu123 commented
> Please explain your ProblemList change or remove it if it was done by mistake.

My bad for letting it sneaked in. I think I manually changed ProblemList.txt for before/after test on another bug.

2021-12-09 20:41 UTC, TheRealMDoerr approved these changes

2021-12-10 13:41 UTC, zhengyu123 commented
/integrate

2021-12-10 13:42 UTC, closed without merging