Backport b46f0b0b1f2ada705f8b5aac9b7d8423699437a1
openjdk/jdk11u-dev pull request #770
Opened 2022-01-17 14:50 UTC by GoeLin

I backport this for parity with 11.0.15-oracle.

I had to do adaptions in the test:
 * I changed the class file version from 62 to 55 in the .jasm file.
 * I replaced  -XX:CompilationMode=quick-only by -XX:TieredStopAtLevel=3
   because the flag CompilationMode is not in 11. I tried to reproduce the bug
   with the new settings, but I can not see the bug. But I also can not reproduce
   it with the original test and the original 17 release.  The test is passing with and 
   without the fix.

2022-01-17 20:59 UTC, phohensee requested changes
There is no .jasm file in the patch.

2022-01-19 07:52 UTC, GoeLin commented
@phohensee, thanks for spotting this!  Fixed.  I will run it through our nightly tests again to make sure the test passes on all platforms we build.

2022-01-19 20:19 UTC, GoeLin commented
I had to update it again... this time my adaptions were missing :(

2022-01-19 22:36 UTC, phohensee approved these changes
Revision lgtm.

2022-01-22 10:00 UTC, GoeLin commented
@phohensee, thanks for reviewing!

/integrate

2022-01-22 10:02 UTC, closed without merging