Backport ddd2951ba91fe3860b92d2f9bad4e0d900f1d650
openjdk/jdk11u-dev pull request #83
Opened 2021-06-30 12:35 UTC by tstuefe

2021-09-08 20:32 UTC, RealCLanger commented
Hi, @tstuefe. Any updates on this one?

2021-09-09 06:50 UTC, tstuefe commented
> Hi, @tstuefe. Any updates on this one?

Its on my list..

2021-09-15 08:06 UTC, tstuefe commented
/label jdk-updates-dev

2021-09-15 20:49 UTC, RealCLanger requested changes
Overall looks good, I just have two formatting remarks which IMHO should be cleaned up.

Other than that, maybe you could enable Github Actions on your repository to get a test run after your next push.

2021-09-15 20:49 UTC, RealCLanger commented on src/hotspot/share/runtime/globals.hpp
> +                  "Print metaspace statistics upon VM exit.")               \
Could you fix the indentation of this line to match the formatting for the other flags around here?

2021-09-15 20:49 UTC, RealCLanger commented on src/hotspot/share/runtime/globals.hpp
> +                                                                            \
one empty line is enough, I'd say.

2021-09-16 04:50 UTC, tstuefe commented
> Overall looks good, I just have two formatting remarks which IMHO should be cleaned up.
> 
> Other than that, maybe you could enable Github Actions on your repository to get a test run after your next push.

Thanks Christoph. GHAs enabled, format changes done. Note that the patch cooked in our internal systems for about two months now, so I don't expect surprises.

2021-09-16 05:27 UTC, RealCLanger commented
> > Overall looks good, I just have two formatting remarks which IMHO should be cleaned up.
> > Other than that, maybe you could enable Github Actions on your repository to get a test run after your next push.
> 
> Thanks Christoph. GHAs enabled, format changes done. Note that the patch cooked in our internal systems for about two months now, so I don't expect surprises.

Sure, LGTM now 👍

2021-09-16 05:27 UTC, RealCLanger approved these changes

2021-09-16 06:22 UTC, tstuefe commented
> > > Overall looks good, I just have two formatting remarks which IMHO should be cleaned up.
> > > Other than that, maybe you could enable Github Actions on your repository to get a test run after your next push.
> > 
> > 
> > Thanks Christoph. GHAs enabled, format changes done. Note that the patch cooked in our internal systems for about two months now, so I don't expect surprises.
> 
> Sure, LGTM now

Thanks. I'll wait for the GHAs to finish, then push.

2021-09-16 06:56 UTC, tstuefe commented
/integrate

2021-09-16 06:58 UTC, closed without merging