Backport f5ee356540d7aa4a7663c0d5d74f5fdb0726b426
openjdk/jdk11u-dev pull request #847
Opened 2022-03-02 11:47 UTC by apavlyutkin

Hello! I'd like to backport

8179503: Java should support GET OCSP calls (dependency)

to jdk11u-dev. This one is required as a dependency for 

8274471: Add support for RSASSA-PSS in OCSP Response

The following changes were done to apply original patch:

src/java.base/share/classes/sun/security/provider/certpath/OCSP.java

- resolved baseline conflict taking due to absent revocation checking code

Verification/regression (20.04/amd64): jdk_security

2022-03-02 12:03 UTC, apavlyutkin commented
@TheRealMDoerr @alexeybakhtin I splitted https://github.com/openjdk/jdk11u-dev/pull/788, this is the 1st part for 8179503

2022-03-02 13:11 UTC, TheRealMDoerr approved these changes
Looks good.

2022-03-02 13:11 UTC, TheRealMDoerr commented on src/java.base/share/classes/sun/security/provider/certpath/OCSP.java
> + * Copyright (c) 2009, 2022, Oracle and/or its affiliates. All rights reserved.
Copyright year update not needed for pure backports when the original change doesn't touch it. May cause merge conflicts. Feel free to revert.

2022-03-02 14:26 UTC, alexeybakhtin commented
Looks good.

2022-03-07 10:39 UTC, GoeLin commented
Please configure Pre-submit tests.

2022-03-08 11:25 UTC, apavlyutkin commented
@GoeLin I've configured pre-submit tests, but they constantly fail on cross-compilation for different target architectures due to absense of required packages. Is that my fault, should I do something else?

2022-03-08 19:23 UTC, TheRealMDoerr commented
A lot of pre-submit tests have failed for other PRs, too. I don't think it's your fault. This change is not platform dependent, so I think your tests are fine.

2022-03-10 11:13 UTC, GoeLin commented
Thanks for the tests, the failures are unrelated.

2022-04-06 07:20 UTC, apavlyutkin commented
jdk11u-fix-no

2023-05-16 20:23 UTC, phax commented
This issue causes a regression, if the OCSP server is not returning the `Content-Length` header which at least happens now and then on a DigiCert server. In that case the `contentLength` is set to `Integer.MAX_VALUE` and `IOUtils.readExactlyNBytes` fails with an `EOFException` because it can`t read `Integer.MAX_VALUE` bytes

See also https://github.com/phax/phase4/issues/124 for my original analysis on the Java 17 problem

2023-05-17 06:06 UTC, apavlyutkin commented
> This issue causes a regression, if the OCSP server is not returning the `Content-Length` header which at least happens now and then on a DigiCert server. In that case the `contentLength` is set to `Integer.MAX_VALUE` and `IOUtils.readExactlyNBytes` fails with an `EOFException` because it can't read `Integer.MAX_VALUE` bytes
> 
> See also [phax/phase4#124](https://github.com/phax/phase4/issues/124) for my original analysis on the Java 17 problem

Thanks a lot, Philip! I will keep it on mind.

2023-05-17 06:14 UTC, apavlyutkin commented
@RealCLanger 

Hi, Chris! As I see you've marked dependent [JDK-8274471](https://bugs.openjdk.org/browse/JDK-8274471) with `jdk11u-todo`. Does it mean I should keep working on this and create depended PR(s)? Previously this one was rejected with `jdk11u-fix-request-no` as inappropriate for jdk11

2023-05-17 06:48 UTC, RealCLanger commented
> This issue causes a regression, if the OCSP server is not returning the `Content-Length` header which at least happens now and then on a DigiCert server. In that case the `contentLength` is set to `Integer.MAX_VALUE` and `IOUtils.readExactlyNBytes` fails with an `EOFException` because it can't read `Integer.MAX_VALUE` bytes
> 
> See also [phax/phase4#124](https://github.com/phax/phase4/issues/124) for my original analysis on the Java 17 problem

This is recorded in JBS now as https://bugs.openjdk.org/browse/JDK-8308255

2023-05-17 06:57 UTC, RealCLanger commented
> @RealCLanger
> 
> Hi, Chris! As I see you've marked dependent [JDK-8274471](https://bugs.openjdk.org/browse/JDK-8274471) with `jdk11u-todo`. Does it mean I should keep working on this and create depended PR(s)? Previously this one was rejected with `jdk11u-fix-request-no` as inappropriate for jdk11

Hi @apavlyutkin,
I have removed jdk11u-fix-no from [JDK-8179503](https://bugs.openjdk.org/browse/JDK-8179503) now, as I think it was backported for Oracle as well (although the backport is not public) and there is justification for backporting this change as well as [JDK-8274471](https://bugs.openjdk.org/browse/JDK-8274471).
You need not care about the jdk11u-todo label. It is just some flagging that helps us keep the JBS filters for open backports lean. You could remove the label once a backport to 11u was merged. But you can also keep the label around for us to clean up.

So, please go ahead with your efforts to backport these two items. As for this PR, I think a merge with master would clean it up and also trigger GHA, hoping for all green results.

2023-05-26 20:15 UTC, phohensee requested changes
@apavlyutkin, there are 494 changed files in the PR vs 3 in the original commit. Looks like a merge issue.

2023-05-30 15:38 UTC, phohensee requested changes
Somehow the last merge changed 494 files, please fix.

2023-05-30 15:51 UTC, apavlyutkin commented
> Somehow the last merge changed 494 files, please fix.

The request was initiated Mar 2, 2022. This is just an upmerge

2023-05-30 16:48 UTC, TheRealMDoerr commented
It may be correct. We can see the actual patch here: https://patch-diff.githubusercontent.com/raw/openjdk/jdk11u-dev/pull/847.patch
The GitHub PR view is broken. We can't see what is being changed. Maybe it's possible to fix it by changing what exactly is supposed to get diffed.

2023-05-31 09:14 UTC, closed without merging