Backport 4def210a22faaec6b47912dd314e6365ea48d28f
openjdk/jdk11u-dev pull request #863
Opened 2022-03-08 18:47 UTC by zhengyu123

This is a followup backport for Cgroup v2 support.

The original patch does not apply cleanly, due to context differences and some of out-of-order backports, conflicts were resolved manually.

In additional:

1) Include partial backport of JDK-8250627.
    - Renamed `Metrics.c` =>  `CgroupMetrics.c`
    - Added native method `isUseContainerSupport()` to `CgroupMetrics.java`
    - Return instance only if `isUseContainerSupport()` is enabled.
   
2) Add `createTempDirectory()` method to `test/lib/jdk/test/lib/Utils.java` for `TestCgroupSubsystemController.java` test

3) Add `import jdk.test.lib.process.OutputAnalyzer;` to `TestDockerMemoryMetrics.java`

Test:

- [x] jtreg containers/docker test on Ubuntu 20.04.4 LTS
- [x] jdk/test/lib/containers/cgroup
- [x] jdk/internal/platform/docker

2022-03-10 14:13 UTC, jerboaa commented on src/java.base/linux/classes/jdk/internal/platform/cgroupv1/CgroupV1Subsystem.java
> +            lines.map(line -> line.split(":"))
We are missing the patch of JDK-8272124 here. Old code was:
https://github.com/openjdk/jdk11u-dev/blob/194b66f6a72437345c458e747e24beb46352537a/src/java.base/linux/classes/jdk/internal/platform/cgroupv1/Metrics.java#L119..L122

Best to use the JDK 17u commit as a base for this:
See: https://github.com/openjdk/jdk17u/commit/f0028333d83c39b434c26f66a6a92e446e7047cd#diff-7d6f202c58b4205f19a9b6c657f4827e9ef132d7433a7bf906b5b640f9f7841fR197

Looking at this again, we should bring in the test changes of JDK-8272124 too (as we are now bringing in those tests with the cgroups v2 backport). It helps to verify this fix is present as well.

2022-03-10 14:21 UTC, jerboaa commented on src/java.base/linux/classes/jdk/internal/platform/cgroupv1/CgroupV1Subsystem.java
> +        if (controllerName != null && base != null) {
We are missing the fix of https://bugs.openjdk.java.net/browse/JDK-8254854 here. Old code was:
https://github.com/openjdk/jdk11u-dev/blob/194b66f6a72437345c458e747e24beb46352537a/src/java.base/linux/classes/jdk/internal/platform/cgroupv1/Metrics.java#L200..L202

See head commit at the time:
https://github.com/openjdk/jdk/commit/a0b687bf

2022-03-10 14:25 UTC, jerboaa commented on src/java.base/linux/classes/jdk/internal/platform/cgroupv1/CgroupV1Subsystem.java
> +    private void setActiveSubSystems() {
function `getSwapEnabled()` from JDK-8250984 is missing here. See:
https://github.com/openjdk/jdk11u-dev/blob/194b66f6a72437345c458e747e24beb46352537a/src/java.base/linux/classes/jdk/internal/platform/cgroupv1/Metrics.java#L246..L249

2022-03-10 19:14 UTC, jerboaa requested changes
A few more comments related to: https://bugs.openjdk.java.net/browse/JDK-8250984

2022-03-10 19:14 UTC, jerboaa commented on src/java.base/linux/classes/jdk/internal/platform/cgroupv1/CgroupV1Subsystem.java
> +    }
This is missing the hunk for https://bugs.openjdk.java.net/browse/JDK-8250984. See:
https://github.com/openjdk/jdk11u-dev/blob/87703322e980e42035d7cf101f04cafdc31fe278/src/java.base/linux/classes/jdk/internal/platform/cgroupv1/Metrics.java#L480..L482

2022-03-10 19:14 UTC, jerboaa commented on src/java.base/linux/classes/jdk/internal/platform/cgroupv1/CgroupV1Subsystem.java
> +        long retval = getLongValue(memory, "memory.memsw.limit_in_bytes");
This is missing the hunk for https://bugs.openjdk.java.net/browse/JDK-8250984. See:
https://github.com/openjdk/jdk11u-dev/blob/87703322e980e42035d7cf101f04cafdc31fe278/src/java.base/linux/classes/jdk/internal/platform/cgroupv1/Metrics.java#L487..L489

2022-03-10 19:14 UTC, jerboaa commented on src/java.base/linux/classes/jdk/internal/platform/cgroupv1/CgroupV1Subsystem.java
> +        return getLongValue(memory, "memory.memsw.max_usage_in_bytes");
This is missing the hunk for https://bugs.openjdk.java.net/browse/JDK-8250984. See:
https://github.com/openjdk/jdk11u-dev/blob/87703322e980e42035d7cf101f04cafdc31fe278/src/java.base/linux/classes/jdk/internal/platform/cgroupv1/Metrics.java#L506..L508

2022-03-10 19:14 UTC, jerboaa commented on src/java.base/linux/classes/jdk/internal/platform/cgroupv1/CgroupV1Subsystem.java
> +        return getLongValue(memory, "memory.memsw.usage_in_bytes");
This is missing the hunk for https://bugs.openjdk.java.net/browse/JDK-8250984. See:
https://github.com/openjdk/jdk11u-dev/blob/87703322e980e42035d7cf101f04cafdc31fe278/src/java.base/linux/classes/jdk/internal/platform/cgroupv1/Metrics.java#L513..L515

2022-03-11 21:23 UTC, zhengyu123 commented
> 

@jerboaa Thanks for the review. I underestimated how many out-of-order backports that affected this backport, especially files without conflicts. I redid `CgroupV1Subsystem.java` and need to go through others.

Thanks.

2022-03-14 13:13 UTC, jerboaa commented
> @jerboaa Thanks for the review. I underestimated how many out-of-order backports that affected this backport, especially files without conflicts. I redid `CgroupV1Subsystem.java` and need to go through others.

Anytime. Please let me know when you are ready for another review.

2022-03-14 23:03 UTC, zhengyu123 commented
> getMemoryAndSwapMaxUsage

Ready for another round, thanks.

-Zhengyu

2022-03-15 15:04 UTC, jerboaa requested changes
A few more fix-ups are needed (see also inline comments):

1. [JDK-8272124](https://bugs.openjdk.java.net/browse/JDK-8272124) fix and test.
2. [JDK-8223396](https://bugs.openjdk.java.net/browse/JDK-8223396). Backport those test changes as a dependency?
3. `PlainRead.java` would need to get the `-2` added as a "good" value. Like here: https://github.com/openjdk/jdk/commit/01875677#diff-fb4f4dbf8943e1dcfd1663922c16f9ed3db403c070bd50979680ec5303756674R48 It's part of the original JDK-8250984 fix, but wasn't part of the 11 backport when it was done. So we should add it with this backport.

2022-03-15 18:28 UTC, jerboaa commented
@zhengyu123 Please also merge latest master into your branch so that GHA tests become clean (baring build/test fail due to this patch).

2022-03-17 17:33 UTC, zhengyu123 commented
> A few more fix-ups are needed (see also inline comments):
> > 3. `PlainRead.java` would need to get the `-2` added as a "good" value. Like here: [openjdk/jdk@01875677#diff-fb4f4dbf8943e1dcfd1663922c16f9ed3db403c070bd50979680ec5303756674R48](https://github.com/openjdk/jdk/commit/01875677#diff-fb4f4dbf8943e1dcfd1663922c16f9ed3db403c070bd50979680ec5303756674R48) It's part of the original JDK-8250984 fix, but wasn't part of the 11 backport when it was done. So we should add it with this backport.

 Even with this change, the test still failed.

2022-03-17 17:36 UTC, jerboaa commented
> > A few more fix-ups are needed (see also inline comments):
> > > 3. `PlainRead.java` would need to get the `-2` added as a "good" value. Like here: [openjdk/jdk@01875677#diff-fb4f4dbf8943e1dcfd1663922c16f9ed3db403c070bd50979680ec5303756674R48](https://github.com/openjdk/jdk/commit/01875677#diff-fb4f4dbf8943e1dcfd1663922c16f9ed3db403c070bd50979680ec5303756674R48) It's part of the original JDK-8250984 fix, but wasn't part of the 11 backport when it was done. So we should add it with this backport.
> 
> Even with this change, the test still failed.

Right. See: https://github.com/openjdk/jdk11u-dev/pull/840#issuecomment-1067065313

2022-03-17 21:00 UTC, zhengyu123 commented
> > > A few more fix-ups are needed (see also inline comments):
> > > > 3. `PlainRead.java` would need to get the `-2` added as a "good" value. Like here: [openjdk/jdk@01875677#diff-fb4f4dbf8943e1dcfd1663922c16f9ed3db403c070bd50979680ec5303756674R48](https://github.com/openjdk/jdk/commit/01875677#diff-fb4f4dbf8943e1dcfd1663922c16f9ed3db403c070bd50979680ec5303756674R48) It's part of the original JDK-8250984 fix, but wasn't part of the 11 backport when it was done. So we should add it with this backport.
> > 
> > 
> > Even with this change, the test still failed.
> 
> Right. See: [#840 (comment)](https://github.com/openjdk/jdk11u-dev/pull/840#issuecomment-1067065313)

Okay. It does not fix the test, I don't think we should include it in this patch, I would prefer to fix it separately.

2022-03-21 18:43 UTC, jerboaa commented
> > > > A few more fix-ups are needed (see also inline comments):
> > > > > 3. `PlainRead.java` would need to get the `-2` added as a "good" value. Like here: [openjdk/jdk@01875677#diff-fb4f4dbf8943e1dcfd1663922c16f9ed3db403c070bd50979680ec5303756674R48](https://github.com/openjdk/jdk/commit/01875677#diff-fb4f4dbf8943e1dcfd1663922c16f9ed3db403c070bd50979680ec5303756674R48) It's part of the original JDK-8250984 fix, but wasn't part of the 11 backport when it was done. So we should add it with this backport.
> > > 
> > > 
> > > Even with this change, the test still failed.
> > 
> > 
> > Right. See: [#840 (comment)](https://github.com/openjdk/jdk11u-dev/pull/840#issuecomment-1067065313)
> 
> Okay. It does not fix the test, I don't think we should include it in this patch, I would prefer to fix it separately.

@zhengyu123 That's fine with me. Please rebase on top of the test changes ([JDK-8223396](https://bugs.openjdk.java.net/browse/JDK-8223396)) integrated recently and backport the test and fix from [JDK-8272124](https://bugs.openjdk.java.net/browse/JDK-8272124). Thank you.

2022-03-22 17:07 UTC, jerboaa commented
> > > > > > A few more fix-ups are needed (see also inline comments):
> > > > > > > 3. `PlainRead.java` would need to get the `-2` added as a "good" value. Like here: [openjdk/jdk@01875677#diff-fb4f4dbf8943e1dcfd1663922c16f9ed3db403c070bd50979680ec5303756674R48](https://github.com/openjdk/jdk/commit/01875677#diff-fb4f4dbf8943e1dcfd1663922c16f9ed3db403c070bd50979680ec5303756674R48) It's part of the original JDK-8250984 fix, but wasn't part of the 11 backport when it was done. So we should add it with this backport.
> > > > > 
> > > > > 
> > > > > Even with this change, the test still failed.
> > > > 
> > > > 
> > > > Right. See: [#840 (comment)](https://github.com/openjdk/jdk11u-dev/pull/840#issuecomment-1067065313)
> > > 
> > > 
> > > Okay. It does not fix the test, I don't think we should include it in this patch, I would prefer to fix it separately.
> > 
> > 
> > @zhengyu123 That's fine with me. Please rebase on top of the test changes ([JDK-8223396](https://bugs.openjdk.java.net/browse/JDK-8223396)) integrated recently and backport the test and fix from [JDK-8272124](https://bugs.openjdk.java.net/browse/JDK-8272124). Thank you.
> 
> I think all 4 PRs are lined up for push. Once this review is done, I will request for approvals for all 4.

Sorry my bad, I thought we were missing the fix from JDK-8272124 but it's there now. As for the test, we can only add that in once JDK-8239559 gets backported.

2022-03-22 17:35 UTC, jerboaa approved these changes
This looks good now. Thanks!

2022-03-23 12:42 UTC, zhengyu123 commented
/integrate

2022-03-23 12:44 UTC, closed without merging