Backport 096e9e5d13183f947089b5c7923890591490a2ce
openjdk/jdk11u-dev pull request #958
Opened 2022-03-29 10:21 UTC by GoeLin

I backport this for parity with 11.0.16-oracle.

platform.m4: Resolved copyright.
jib-proviles.js: macos-aarch64 not listed. Skipped.

2022-03-29 10:35 UTC, TheRealMDoerr requested changes
Please fix typo.

2022-03-29 10:35 UTC, TheRealMDoerr commented on make/conf/jib-profiles.js
> +            platform: "jacos-x64",
Typo!

2022-03-29 12:41 UTC, GoeLin commented
Thanks for spotting this! Fixed.

2022-03-29 12:41 UTC, TheRealMDoerr approved these changes
LGTM.

2022-04-18 19:28 UTC, VladimirKempik approved these changes

2022-04-29 10:10 UTC, GoeLin commented
Pre-submit failures
gc/TestNumWorkerOutput.java#id1 known CMS issue on x86_32, unrelated.
Linux x64: build dependencies, unrelated

2022-04-29 10:10 UTC, GoeLin commented
/integrate

2022-04-29 10:12 UTC, closed without merging