Backport bc42e7cbbfd586308338bfdf535c4fcab0cdbc48
openjdk/jdk11u-dev pull request #976
Opened 2022-04-01 06:21 UTC by tstuefe

Would like to backport to jdk17u. Helps with C-heap performance analysis. Low risk. Does not apply cleanly (copyright, and code moved around a bit since then).

2022-04-04 09:30 UTC, TheRealMDoerr requested changes
Please fix Copyright header. Otherwise, good.

2022-04-04 09:30 UTC, TheRealMDoerr commented on src/hotspot/os/linux/os_linux.cpp
> +  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
`*` missing.

2022-04-04 16:54 UTC, tstuefe commented on src/hotspot/os/linux/os_linux.cpp
> +  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
Thanks for catching that!

2022-04-04 17:50 UTC, TheRealMDoerr approved these changes
Thanks for the update!

2022-04-05 03:26 UTC, tstuefe commented
/integrate

2022-04-05 03:27 UTC, closed without merging